changelog:
  categories:
    - title: '🚀 Features'
      labels:
        - 'feature'
        - 'enhancement'
    - title: '🐛 Bug Fixes'
      labels:
        - 'bug'
        - 'fix'
  exclude:
    labels:
      - 'chore'
    authors:
      - 'github-actions[bot]'
